config_on_startup: false
publish:
  nav:
    relposned: true
    status: true
    pvt: true
  rxm:
    rtcm: true
gnss:
  gps: true
  glonass: true
  galileo: true
  beidou: true
dynamic_model: portable
frame_id: gnss
debug: 0
rate: 10.0
nav_rate: 1
